sudo: required

language: generic

services: 
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t bomian/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true bomian/docker-react-app npm run test -- --coverage

after_duccess: 
  - echo "Test Success"